### PR TITLE
corrected file name for full-width page template

### PR DESCRIPTION
**Pull request by JulieKuehl**
per the WordPress Codex: "Important! Do not use page- as a prefix, as WordPress will interpret the file as a specialized template, meant to apply to only one page on your site."

### CODE REVIEW

**Comment by jrtashjian** [comment]
Good catch and thanks for the pull request!

It would be better to create a `templates` directory and place this file inside of it in case we add other templates in the future. I would suggest dropping the `page` prefix altogether and just have it as `full-width.php`. After you make those two changes I think we're good to pull this in.

Keep in mind that once this change is complete you will have to reassign this page template for each page using it in your dev environment.

**Review by jrtashjian — CHANGES_REQUESTED** [review]
Thanks for making the update! One last fix and we can merge it in. The last commit included some changes to the src/scss/style.css file and isn't related to this original pull request. Could you remove/revert those changes? After that we can pull this in.

**Comment by JulieKuehl** [comment]
Ok, I learned a few things about git today, unexpectedly. :-) But I think the PR is cleaned up now.

**Comment by jrtashjian** [comment]
The `src/scss/style.css` file still exists. Can you delete it and re-commit?

**Comment by JulieKuehl** [comment]
OK. One more time. I think it's all cleaned up now.

**Review by jrtashjian — APPROVED** [review]

**Comment by jrtashjian** [comment]
Awesome, thanks @JulieKuehl for contributing! 😄

**Pull request merged**
