### PR TITLE
Replace dependency gulp-combine-media-queries

### LINKED ISSUE #2: gulp build error
After a fresh install (or several), I keep getting an error on the first `gulp build`: https://cloudup.com/c7Tg-AETE39

???
Help?

### PR DESCRIPTION
**Pull request by jrtashjian**
`gulp-combine-media-queries` is causing compiling issues on newer
versions of Node/NPM.

`gulp-merge-media-queries` seems to fix those issues.

Fixes #2

### CODE REVIEW

**Comment by benleivian** [comment]
Nice! I can test on my end, but i'm sure it's gtg.

**Comment by wardandrews** [comment]
W()()t

## 

Ward Andrews
480-477-9205 x700 <480-744-9205%20x700>

Drawbackwards
502 South College Avenue, Suite 307
Tempe, Arizona 85281
drawbackwards.com

We Design Business Success.

**Comment by benleivian** [comment]
Works good for me (Node v6.3.1)

**Comment by JulieKuehl** [comment]
thanks so much!

**Pull request merged**
